#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

git_url = "https://github.com/owejow/fastai_v2_notes/tree/master/"

def custom_doc_links(name): return None